name: Android CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK (Java 17 is stable for Android Gradle 8+)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # 3️⃣ Give permission to gradlew script
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4️⃣ (Optional but recommended) Remove Gradle cache to avoid stale icons/resources
      - name: Remove Gradle cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf ~/.gradle/native
          rm -rf ~/.gradle/wrapper

      # 5️⃣ Clean old build artifacts (ensures icons and app name updates)
      - name: Clean project
        run: ./gradlew clean

      # 6️⃣ Build debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 7️⃣ Upload Debug APK as artifact (for download)
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
